name: Build pre-release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build_shared.yml
    with:
      ref: ${{ github.ref }}
      tag: v0.0.0-${{ github.sha }}
      strip_rc: true
